import React, { useState } from "react";
import { Download, Upload, Database, RefreshCw, CheckCircle, FileJson } from "lucide-react";
import { Client, Product, Invoice, CompanySettings } from "../types";

interface BackupViewProps {
  clients: Client[];
  products: Product[];
  invoices: Invoice[];
  companySettings: CompanySettings | null;
  onRestoreData: (restored: {
    clients: any[];
    products: any[];
    invoices: any[];
    companySettings: any;
  }) => Promise<void>;
}

export default function BackupView({ clients, products, invoices, companySettings, onRestoreData }: BackupViewProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [isImporting, setIsImporting] = useState(false);

  const handleExport = () => {
    try {
      setIsExporting(true);
      const backupPayload = {
        app: "MS Billing System",
        exportedAt: new Date().toISOString(),
        data: {
          clients,
          products,
          invoices,
          companySettings
        }
      };

      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(backupPayload, null, 2));
      const downloadAnchor = document.createElement("a");
      downloadAnchor.setAttribute("href", dataStr);
      downloadAnchor.setAttribute("download", `ms_billing_backup_${new Date().toISOString().split("T")[0]}.json`);
      document.body.appendChild(downloadAnchor);
      downloadAnchor.click();
      downloadAnchor.remove();
      
      alert("Backup JSON file generated and downloaded successfully!");
    } catch (err: any) {
      alert("Backup generation failure: " + err.message);
    } finally {
      setIsExporting(false);
    }
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!confirm("RESTORE DATA WARNING:\nThis action will overwrite your current cloud database parameters with the backup contents. Are you sure you want to proceed?")) {
      e.target.value = "";
      return;
    }

    setIsImporting(true);
    const reader = new FileReader();
    reader.onload = async (event) => {
      try {
        const json = JSON.parse(event.target?.result as string);
        if (json.app !== "MS Billing System" || !json.data) {
          throw new Error("Invalid backup signature. Please upload files generated by MS Billing Software.");
        }

        await onRestoreData(json.data);
        alert("Success: Ledger backup contents successfully synchronized and written to real-time Firestore!");
      } catch (err: any) {
        alert("Import operational failure: " + err.message);
      } finally {
        setIsImporting(false);
        e.target.value = "";
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="flex flex-col gap-6 animate-fadeIn select-none">
      {/* Header */}
      <div className="flex justify-between items-center bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
        <div>
          <h2 className="text-xl font-bold text-gray-800">Backup & Restore</h2>
          <p className="text-xs text-gray-500 mt-1">Export database parameters as standardized JSON formats, or restore backups instantly to Firestore.</p>
        </div>
        <div className="w-10 h-10 rounded-full bg-blue-50 text-[#0c4cb3] flex items-center justify-center font-bold">
          <Database size={18} />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl">
        {/* Export Box */}
        <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm flex flex-col justify-between gap-5">
          <div className="space-y-2">
            <div className="w-10 h-10 rounded-xl bg-blue-50 text-[#0c4cb3] flex items-center justify-center mb-3">
              <Download size={20} />
            </div>
            <h3 className="text-sm font-bold text-gray-800">Cloud Data Export</h3>
            <p className="text-xs text-gray-500 leading-relaxed">
              Consolidate and download all system settings, active inventory stock categories, outstanding customer records and historical TAX bills into a secure offline package.
            </p>
          </div>

          <div className="pt-2">
            <button
              onClick={handleExport}
              disabled={isExporting}
              className="w-full bg-[#0c4cb3] hover:bg-[#063280] disabled:opacity-50 text-white font-semibold text-xs py-3 rounded-xl flex items-center justify-center gap-2 transition-all cursor-pointer shadow-md shadow-[#0c4cb3]/10"
            >
              <FileJson size={14} />
              <span>{isExporting ? "Generating Package..." : "Export Database JSON"}</span>
            </button>
          </div>
        </div>

        {/* Import Box */}
        <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm flex flex-col justify-between gap-5">
          <div className="space-y-2">
            <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center mb-3">
              <Upload size={20} />
            </div>
            <h3 className="text-sm font-bold text-gray-800">Restore Cloud Snapshot</h3>
            <p className="text-xs text-gray-500 leading-relaxed">
              Overhaul local cloud state variables by feeding historical backup templates into standard REST pipelines. All changes synchronize dynamically to database indexes.
            </p>
          </div>

          <div className="pt-2">
            <label className="w-full text-center py-3 border border-dashed border-[#0b4ebd] bg-[#eff6ff] hover:bg-[#dbeafe] text-[#0b4ebd] text-xs font-semibold rounded-xl cursor-pointer transition-colors block">
              <span>{isImporting ? "Synchronizing Storage..." : "Upload JSON backup"}</span>
              <input
                type="file"
                accept=".json"
                onChange={handleImport}
                disabled={isImporting}
                className="hidden"
              />
            </label>
          </div>
        </div>
      </div>

      {/* Cloud Status indicator panel */}
      <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm max-w-4xl space-y-4">
        <h4 className="text-xs font-bold text-gray-800 flex items-center gap-2 pb-2 border-b border-gray-100">
          <CheckCircle size={14} className="text-green-500" />
          <span>Active Real-time Synchronization Metrics</span>
        </h4>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-center">
          <div className="p-3 bg-gray-50 rounded-xl">
            <span className="text-[10px] font-bold text-gray-400 uppercase">Clients Synced</span>
            <p className="text-sm font-extrabold text-gray-800 mt-1">{clients.length}</p>
          </div>
          <div className="p-3 bg-gray-50 rounded-xl">
            <span className="text-[10px] font-bold text-gray-400 uppercase">Products Loaded</span>
            <p className="text-sm font-extrabold text-gray-800 mt-1">{products.length}</p>
          </div>
          <div className="p-3 bg-gray-50 rounded-xl">
            <span className="text-[10px] font-bold text-gray-400 uppercase">Invoices Listed</span>
            <p className="text-sm font-extrabold text-gray-800 mt-1">{invoices.length}</p>
          </div>
          <div className="p-3 bg-gray-50 rounded-xl">
            <span className="text-[10px] font-bold text-gray-400 uppercase">Profile Link</span>
            <p className="text-xs font-extrabold text-green-600 mt-1.5 uppercase leading-none">ACTIVE</p>
          </div>
        </div>
      </div>
    </div>
  );
}
